language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install twisted
  - pip install boto3
  - pip install https://github.com/matrix-org/synapse/tarball/master
# command to run tests
script:
  - PYTHONPATH=. trial test_s3
